/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    roles: Role;
    courses: Course;
    'course-modules': CourseModule;
    'course-excursions': CourseExcursion;
    'course-practice-units': CoursePracticeUnit;
    'course-speakers': CourseSpeaker;
    'course-gardens': CourseGarden;
    'course-shared-documents': CourseSharedDocument;
    'course-video-lessons': CourseVideoLesson;
    plants: Plant;
    'plant-families': PlantFamily;
    'plant-groups': PlantGroup;
    'plant-toxicity-levels': PlantToxicityLevel;
    'plant-recognition-features': PlantRecognitionFeature;
    'plant-images': PlantImage;
    'plant-parts': PlantPart;
    'plant-substances': PlantSubstance;
    'plant-effects': PlantEffect;
    'web-images': WebImage;
    'web-image-categories': WebImageCategory;
    'web-pages': WebPage;
    'web-partners': WebPartner;
    'web-socials': WebSocial;
    'web-books': WebBook;
    'web-text-blocks': WebTextBlock;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      enrolledCourses: 'courses';
      attendedModules: 'course-modules';
    };
    courses: {
      modules: 'course-modules';
    };
    plants: {
      images: 'plant-images';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    'course-modules': CourseModulesSelect<false> | CourseModulesSelect<true>;
    'course-excursions': CourseExcursionsSelect<false> | CourseExcursionsSelect<true>;
    'course-practice-units': CoursePracticeUnitsSelect<false> | CoursePracticeUnitsSelect<true>;
    'course-speakers': CourseSpeakersSelect<false> | CourseSpeakersSelect<true>;
    'course-gardens': CourseGardensSelect<false> | CourseGardensSelect<true>;
    'course-shared-documents': CourseSharedDocumentsSelect<false> | CourseSharedDocumentsSelect<true>;
    'course-video-lessons': CourseVideoLessonsSelect<false> | CourseVideoLessonsSelect<true>;
    plants: PlantsSelect<false> | PlantsSelect<true>;
    'plant-families': PlantFamiliesSelect<false> | PlantFamiliesSelect<true>;
    'plant-groups': PlantGroupsSelect<false> | PlantGroupsSelect<true>;
    'plant-toxicity-levels': PlantToxicityLevelsSelect<false> | PlantToxicityLevelsSelect<true>;
    'plant-recognition-features': PlantRecognitionFeaturesSelect<false> | PlantRecognitionFeaturesSelect<true>;
    'plant-images': PlantImagesSelect<false> | PlantImagesSelect<true>;
    'plant-parts': PlantPartsSelect<false> | PlantPartsSelect<true>;
    'plant-substances': PlantSubstancesSelect<false> | PlantSubstancesSelect<true>;
    'plant-effects': PlantEffectsSelect<false> | PlantEffectsSelect<true>;
    'web-images': WebImagesSelect<false> | WebImagesSelect<true>;
    'web-image-categories': WebImageCategoriesSelect<false> | WebImageCategoriesSelect<true>;
    'web-pages': WebPagesSelect<false> | WebPagesSelect<true>;
    'web-partners': WebPartnersSelect<false> | WebPartnersSelect<true>;
    'web-socials': WebSocialsSelect<false> | WebSocialsSelect<true>;
    'web-books': WebBooksSelect<false> | WebBooksSelect<true>;
    'web-text-blocks': WebTextBlocksSelect<false> | WebTextBlocksSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'web-footer': WebFooter;
    'web-header': WebHeader;
    'web-sidebar': WebSidebar;
    contact: Contact;
  };
  globalsSelect: {
    'web-footer': WebFooterSelect<false> | WebFooterSelect<true>;
    'web-header': WebHeaderSelect<false> | WebHeaderSelect<true>;
    'web-sidebar': WebSidebarSelect<false> | WebSidebarSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Manage user accounts and their roles
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  /**
   * User can have multiple roles (e.g., Dashboard User + Quiz Player)
   */
  roles: (number | Role)[];
  /**
   * Internal notes about the user (not visible to the user)
   */
  notes?: string | null;
  /**
   * Courses this user is enrolled in
   */
  enrolledCourses?: {
    docs?: (number | Course)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Modules this user has attended
   */
  attendedModules?: {
    docs?: (number | CourseModule)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  address?: {
    place?: string | null;
    zip?: string | null;
    street?: string | null;
  };
  birthDate?: string | null;
  birthPlace?: string | null;
  phone?: string | null;
  taxNumber?: string | null;
  profilename?: string | null;
  description?: string | null;
  linkedin?: string | null;
  instagram?: string | null;
  facebook?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Manage user roles and permissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  /**
   * Display name of the role
   */
  name: string;
  /**
   * Unique identifier for the role
   */
  slug:
    | 'super-admin'
    | 'administrator'
    | 'content-creator'
    | 'dashboard-user'
    | 'quiz-player'
    | 'demo-dashboard-user'
    | 'demo-quiz-player';
  /**
   * What can users with this role do?
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  /**
   * Unique course identifier (e.g., K1, K2, K3)
   */
  name: string;
  /**
   * Location where the course takes place
   */
  place: 'unterland' | 'pustertal' | 'vinschgau';
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Current status of the course
   */
  status: 'open' | 'running' | 'closed';
  /**
   * Modules that belong to this course
   */
  modules?: {
    docs?: (number | CourseModule)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Users enrolled in this course
   */
  participants?: (number | User)[] | null;
  /**
   * Shared documents associated with this course
   */
  sharedDocuments?: (number | CourseSharedDocument)[] | null;
  /**
   * Video lessons associated with this course
   */
  videoLessons?: (number | CourseVideoLesson)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-modules".
 */
export interface CourseModule {
  id: number;
  /**
   * Auto-generated or custom title for the module
   */
  title: string;
  /**
   * The course this module belongs to
   */
  course: number | Course;
  /**
   * Date when the module takes place
   */
  date: string;
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Participants who attended this specific module
   */
  participants?: (number | User)[] | null;
  /**
   * Plants associated with this module
   */
  plants?: (number | Plant)[] | null;
  /**
   * Excursions associated with this module
   */
  excursions?: (number | CourseExcursion)[] | null;
  /**
   * Practice units associated with this module
   */
  practiceUnits?: (number | CoursePracticeUnit)[] | null;
  /**
   * Speakers associated with this module
   */
  speakers?: (number | CourseSpeaker)[] | null;
  /**
   * Gardens associated with this module
   */
  gardens?: (number | CourseGarden)[] | null;
  /**
   * Shared documents associated with this module
   */
  sharedDocuments?: (number | CourseSharedDocument)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plants".
 */
export interface Plant {
  id: number;
  /**
   * The botanical family this plant belongs to
   */
  family: number | PlantFamily;
  /**
   * German name of the plant
   */
  germanName: string;
  /**
   * Scientific/Latin name of the plant
   */
  scientificName: string;
  germanNameVariations?:
    | {
        variation: string;
        id?: string | null;
      }[]
    | null;
  scientificNameVariations?:
    | {
        variation: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Images that belong to this plant (managed in Plant Images)
   */
  images?: {
    docs?: (number | PlantImage)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * The groups this plant belongs to
   */
  groups?: (number | PlantGroup)[] | null;
  /**
   * The toxicity level of this plant, if applicable
   */
  toxicityLevel?: (number | null) | PlantToxicityLevel;
  /**
   * Substances on specific plant parts and their effects (managed in Plant Part Substances)
   */
  plantPartSubstances?:
    | {
        plantPart: number | PlantPart;
        plantSubstance: number | PlantSubstance;
        plantEffect?: (number | null) | PlantEffect;
        id?: string | null;
      }[]
    | null;
  /**
   * Recognition features of this plant
   */
  recognitionFeatures?: (number | PlantRecognitionFeature)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plant-families".
 */
export interface PlantFamily {
  id: number;
  /**
   * German name of the plant family
   */
  germanName: string;
  /**
   * Scientific/Latin name of the plant family
   */
  scientificName: string;
  germanNameVariations?:
    | {
        variation: string;
        id?: string | null;
      }[]
    | null;
  scientificNameVariations?:
    | {
        variation: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plant-images".
 */
export interface PlantImage {
  id: number;
  /**
   * The plant this image belongs to (one plant per image)
   */
  plant: number | Plant;
  recognitionFeatures?: (number | PlantRecognitionFeature)[] | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail_jpeg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnail_webp?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnail_avif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    mobile_jpeg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    mobile_webp?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    mobile_avif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet_jpeg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet_webp?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet_avif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop_jpeg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop_webp?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop_avif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plant-recognition-features".
 */
export interface PlantRecognitionFeature {
  id: number;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plant-groups".
 */
export interface PlantGroup {
  id: number;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plant-toxicity-levels".
 */
export interface PlantToxicityLevel {
  id: number;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plant-parts".
 */
export interface PlantPart {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plant-substances".
 */
export interface PlantSubstance {
  id: number;
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plant-effects".
 */
export interface PlantEffect {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-excursions".
 */
export interface CourseExcursion {
  id: number;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-practice-units".
 */
export interface CoursePracticeUnit {
  id: number;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-speakers".
 */
export interface CourseSpeaker {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-gardens".
 */
export interface CourseGarden {
  id: number;
  name: string;
  link: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-shared-documents".
 */
export interface CourseSharedDocument {
  id: number;
  filename: string;
  filetype: string;
  url: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-video-lessons".
 */
export interface CourseVideoLesson {
  id: number;
  title: string;
  youtubeURL?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-images".
 */
export interface WebImage {
  id: number;
  alt: string;
  category?: (number | WebImageCategory)[] | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail_jpeg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnail_webp?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnail_avif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    mobile_jpeg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    mobile_webp?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    mobile_avif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet_jpeg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet_webp?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet_avif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop_jpeg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop_webp?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop_avif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-image-categories".
 */
export interface WebImageCategory {
  id: number;
  title: string;
  description?: string | null;
  showInGallery?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-pages".
 */
export interface WebPage {
  id: number;
  title?: string | null;
  slug: string;
  blocks?:
    | (
        | {
            content?: {
              title?: string | null;
              items?:
                | {
                    title: string;
                    content?: {
                      root: {
                        type: string;
                        children: {
                          type: any;
                          version: number;
                          [k: string]: unknown;
                        }[];
                        direction: ('ltr' | 'rtl') | null;
                        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                        indent: number;
                        version: number;
                      };
                      [k: string]: unknown;
                    } | null;
                    id?: string | null;
                  }[]
                | null;
            };
            settings: {
              spacing: {
                marginTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                marginBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
              };
              style: 'light' | 'gray' | 'dark';
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'web-accordions';
          }
        | {
            content: {
              text: string;
            };
            settings: {
              spacing: {
                marginTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                marginBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
              };
              style: 'light' | 'gray' | 'dark';
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'web-animatedText';
          }
        | {
            content?: {
              title?: string | null;
              /**
               * Select books to display in this list
               */
              books?: (number | WebBook)[] | null;
            };
            settings: {
              spacing: {
                marginTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                marginBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
              };
              style: 'light' | 'gray' | 'dark';
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'web-book-list';
          }
        | {
            content?: {
              title?: string | null;
              /**
               * Select courses to display in this list
               */
              courses?: (number | Course)[] | null;
            };
            settings: {
              spacing: {
                marginTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                marginBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
              };
              style: 'light' | 'gray' | 'dark';
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'web-course-list';
          }
        | {
            content: {
              image: number | WebImage;
              title: string;
            };
            settings: {
              spacing: {
                marginTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                marginBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
              };
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'web-hero-large';
          }
        | {
            content: {
              image?: (number | null) | WebImage;
              title: string;
              link?: {
                text?: string | null;
                href?: string | null;
                target?: ('_self' | '_blank' | '_parent' | '_top' | '_unfencedTop') | null;
              };
            };
            settings: {
              spacing: {
                marginTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                marginBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
              };
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'web-hero-small';
          }
        | {
            content?: {
              links?:
                | {
                    label: string;
                    url: string;
                    image: number | WebImage;
                    target?: ('_self' | '_blank') | null;
                    id?: string | null;
                  }[]
                | null;
            };
            settings: {
              spacing: {
                marginTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                marginBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
              };
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'web-highlighted-links';
          }
        | {
            content?: {
              title?: string | null;
              image?: (number | null) | WebImage;
              textTop?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              textHighlight?: string | null;
              textBottom?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              link?: {
                text?: string | null;
                href?: string | null;
                target?: ('_self' | '_blank' | '_parent' | '_top' | '_unfencedTop') | null;
              };
            };
            settings: {
              spacing: {
                marginTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                marginBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
              };
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'web-image-text';
          }
        | {
            content?: {
              infos?:
                | {
                    infos: {
                      title?: string | null;
                      text?: {
                        root: {
                          type: string;
                          children: {
                            type: any;
                            version: number;
                            [k: string]: unknown;
                          }[];
                          direction: ('ltr' | 'rtl') | null;
                          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                          indent: number;
                          version: number;
                        };
                        [k: string]: unknown;
                      } | null;
                    };
                    link?: {
                      text?: string | null;
                      href?: string | null;
                      target?: ('_self' | '_blank' | '_parent' | '_top' | '_unfencedTop') | null;
                    };
                    id?: string | null;
                  }[]
                | null;
            };
            settings: {
              spacing: {
                marginTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                marginBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
              };
              style: 'light' | 'gray' | 'dark';
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'web-infos';
          }
        | {
            content?: {
              image?: (number | null) | WebImage;
            };
            settings: {
              spacing: {
                marginTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                marginBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
              };
              style: 'light' | 'gray' | 'dark';
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'web-mood-picture';
          }
        | {
            content?: {
              cards?:
                | {
                    image?: (number | null) | WebImage;
                    info?: string | null;
                    date?: string | null;
                    title?: string | null;
                    link?: {
                      text?: string | null;
                      href?: string | null;
                      target?: ('_self' | '_blank' | '_parent' | '_top' | '_unfencedTop') | null;
                    };
                    id?: string | null;
                  }[]
                | null;
            };
            settings: {
              spacing: {
                marginTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                marginBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
              };
              style: 'light' | 'gray' | 'dark';
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'web-swiper-card';
          }
        | {
            content?: {
              title?: string | null;
              items?:
                | {
                    image?: (number | null) | WebImage;
                    infos?: string | null;
                    title?: string | null;
                    description?: {
                      root: {
                        type: string;
                        children: {
                          type: any;
                          version: number;
                          [k: string]: unknown;
                        }[];
                        direction: ('ltr' | 'rtl') | null;
                        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                        indent: number;
                        version: number;
                      };
                      [k: string]: unknown;
                    } | null;
                    link?: {
                      text?: string | null;
                      href?: string | null;
                      target?: ('_self' | '_blank' | '_parent' | '_top' | '_unfencedTop') | null;
                    };
                    id?: string | null;
                  }[]
                | null;
            };
            settings: {
              spacing: {
                marginTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                marginBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
              };
              style: 'light' | 'gray' | 'dark';
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'web-swiper-large';
          }
        | {
            content?: {
              slides?:
                | {
                    title?: string | null;
                    images?:
                      | {
                          image?: (number | null) | WebImage;
                          id?: string | null;
                        }[]
                      | null;
                    id?: string | null;
                  }[]
                | null;
            };
            settings: {
              spacing: {
                marginTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                marginBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
              };
              style: 'light' | 'gray' | 'dark';
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'web-swiper-simple';
          }
        | {
            content: {
              title?: string | null;
              content: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              link?: {
                text?: string | null;
                href?: string | null;
                target?: ('_self' | '_blank' | '_parent' | '_top' | '_unfencedTop') | null;
              };
            };
            settings: {
              spacing: {
                marginTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                marginBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingTop: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
                paddingBottom: 'none' | 'small' | 'medium' | 'large' | 'xlarge';
              };
              style: 'light' | 'gray' | 'dark';
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'web-text-element';
          }
      )[]
    | null;
  description?: string | null;
  /**
   * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
   */
  image?: (number | null) | WebImage;
  /**
   * Relevant keywords for this page (one per line)
   */
  keywords?: string[] | null;
  /**
   * Prevent search engines from indexing this page
   */
  noIndex?: boolean | null;
  /**
   * The canonical URL for this page (leave empty to use current URL)
   */
  canonical?: string | null;
  /**
   * The schema.org type for structured data
   */
  schemaType?: ('WebPage' | 'Article' | 'BlogPosting' | 'Course' | 'AboutPage' | 'ContactPage' | 'FAQPage') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-books".
 */
export interface WebBook {
  id: number;
  title: string;
  infos: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cover?: (number | null) | WebImage;
  link?: {
    text?: string | null;
    href?: string | null;
    target?: ('_self' | '_blank' | '_parent' | '_top' | '_unfencedTop') | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-partners".
 */
export interface WebPartner {
  id: number;
  name?: string | null;
  link?: {
    text?: string | null;
    href?: string | null;
    target?: ('_self' | '_blank' | '_parent' | '_top' | '_unfencedTop') | null;
  };
  image?: (number | null) | WebImage;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-socials".
 */
export interface WebSocial {
  id: number;
  link?: {
    text?: string | null;
    href?: string | null;
    target?: ('_self' | '_blank' | '_parent' | '_top' | '_unfencedTop') | null;
  };
  icon?: ('facebook' | 'instagram') | null;
  backgroundImage?: (number | null) | WebImage;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-text-blocks".
 */
export interface WebTextBlock {
  id: number;
  slug: string;
  value: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'course-modules';
        value: number | CourseModule;
      } | null)
    | ({
        relationTo: 'course-excursions';
        value: number | CourseExcursion;
      } | null)
    | ({
        relationTo: 'course-practice-units';
        value: number | CoursePracticeUnit;
      } | null)
    | ({
        relationTo: 'course-speakers';
        value: number | CourseSpeaker;
      } | null)
    | ({
        relationTo: 'course-gardens';
        value: number | CourseGarden;
      } | null)
    | ({
        relationTo: 'course-shared-documents';
        value: number | CourseSharedDocument;
      } | null)
    | ({
        relationTo: 'course-video-lessons';
        value: number | CourseVideoLesson;
      } | null)
    | ({
        relationTo: 'plants';
        value: number | Plant;
      } | null)
    | ({
        relationTo: 'plant-families';
        value: number | PlantFamily;
      } | null)
    | ({
        relationTo: 'plant-groups';
        value: number | PlantGroup;
      } | null)
    | ({
        relationTo: 'plant-toxicity-levels';
        value: number | PlantToxicityLevel;
      } | null)
    | ({
        relationTo: 'plant-recognition-features';
        value: number | PlantRecognitionFeature;
      } | null)
    | ({
        relationTo: 'plant-images';
        value: number | PlantImage;
      } | null)
    | ({
        relationTo: 'plant-parts';
        value: number | PlantPart;
      } | null)
    | ({
        relationTo: 'plant-substances';
        value: number | PlantSubstance;
      } | null)
    | ({
        relationTo: 'plant-effects';
        value: number | PlantEffect;
      } | null)
    | ({
        relationTo: 'web-images';
        value: number | WebImage;
      } | null)
    | ({
        relationTo: 'web-image-categories';
        value: number | WebImageCategory;
      } | null)
    | ({
        relationTo: 'web-pages';
        value: number | WebPage;
      } | null)
    | ({
        relationTo: 'web-partners';
        value: number | WebPartner;
      } | null)
    | ({
        relationTo: 'web-socials';
        value: number | WebSocial;
      } | null)
    | ({
        relationTo: 'web-books';
        value: number | WebBook;
      } | null)
    | ({
        relationTo: 'web-text-blocks';
        value: number | WebTextBlock;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  roles?: T;
  notes?: T;
  enrolledCourses?: T;
  attendedModules?: T;
  address?:
    | T
    | {
        place?: T;
        zip?: T;
        street?: T;
      };
  birthDate?: T;
  birthPlace?: T;
  phone?: T;
  taxNumber?: T;
  profilename?: T;
  description?: T;
  linkedin?: T;
  instagram?: T;
  facebook?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  name?: T;
  place?: T;
  description?: T;
  status?: T;
  modules?: T;
  participants?: T;
  sharedDocuments?: T;
  videoLessons?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-modules_select".
 */
export interface CourseModulesSelect<T extends boolean = true> {
  title?: T;
  course?: T;
  date?: T;
  notes?: T;
  participants?: T;
  plants?: T;
  excursions?: T;
  practiceUnits?: T;
  speakers?: T;
  gardens?: T;
  sharedDocuments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-excursions_select".
 */
export interface CourseExcursionsSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-practice-units_select".
 */
export interface CoursePracticeUnitsSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-speakers_select".
 */
export interface CourseSpeakersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-gardens_select".
 */
export interface CourseGardensSelect<T extends boolean = true> {
  name?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-shared-documents_select".
 */
export interface CourseSharedDocumentsSelect<T extends boolean = true> {
  filename?: T;
  filetype?: T;
  url?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-video-lessons_select".
 */
export interface CourseVideoLessonsSelect<T extends boolean = true> {
  title?: T;
  youtubeURL?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plants_select".
 */
export interface PlantsSelect<T extends boolean = true> {
  family?: T;
  germanName?: T;
  scientificName?: T;
  germanNameVariations?:
    | T
    | {
        variation?: T;
        id?: T;
      };
  scientificNameVariations?:
    | T
    | {
        variation?: T;
        id?: T;
      };
  images?: T;
  groups?: T;
  toxicityLevel?: T;
  plantPartSubstances?:
    | T
    | {
        plantPart?: T;
        plantSubstance?: T;
        plantEffect?: T;
        id?: T;
      };
  recognitionFeatures?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plant-families_select".
 */
export interface PlantFamiliesSelect<T extends boolean = true> {
  germanName?: T;
  scientificName?: T;
  germanNameVariations?:
    | T
    | {
        variation?: T;
        id?: T;
      };
  scientificNameVariations?:
    | T
    | {
        variation?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plant-groups_select".
 */
export interface PlantGroupsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plant-toxicity-levels_select".
 */
export interface PlantToxicityLevelsSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plant-recognition-features_select".
 */
export interface PlantRecognitionFeaturesSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plant-images_select".
 */
export interface PlantImagesSelect<T extends boolean = true> {
  plant?: T;
  recognitionFeatures?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail_jpeg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbnail_webp?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbnail_avif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        mobile_jpeg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        mobile_webp?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        mobile_avif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet_jpeg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet_webp?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet_avif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop_jpeg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop_webp?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop_avif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plant-parts_select".
 */
export interface PlantPartsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plant-substances_select".
 */
export interface PlantSubstancesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plant-effects_select".
 */
export interface PlantEffectsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-images_select".
 */
export interface WebImagesSelect<T extends boolean = true> {
  alt?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail_jpeg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbnail_webp?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbnail_avif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        mobile_jpeg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        mobile_webp?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        mobile_avif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet_jpeg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet_webp?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet_avif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop_jpeg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop_webp?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop_avif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-image-categories_select".
 */
export interface WebImageCategoriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  showInGallery?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-pages_select".
 */
export interface WebPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  blocks?:
    | T
    | {
        'web-accordions'?:
          | T
          | {
              content?:
                | T
                | {
                    title?: T;
                    items?:
                      | T
                      | {
                          title?: T;
                          content?: T;
                          id?: T;
                        };
                  };
              settings?:
                | T
                | {
                    spacing?:
                      | T
                      | {
                          marginTop?: T;
                          marginBottom?: T;
                          paddingTop?: T;
                          paddingBottom?: T;
                        };
                    style?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'web-animatedText'?:
          | T
          | {
              content?:
                | T
                | {
                    text?: T;
                  };
              settings?:
                | T
                | {
                    spacing?:
                      | T
                      | {
                          marginTop?: T;
                          marginBottom?: T;
                          paddingTop?: T;
                          paddingBottom?: T;
                        };
                    style?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'web-book-list'?:
          | T
          | {
              content?:
                | T
                | {
                    title?: T;
                    books?: T;
                  };
              settings?:
                | T
                | {
                    spacing?:
                      | T
                      | {
                          marginTop?: T;
                          marginBottom?: T;
                          paddingTop?: T;
                          paddingBottom?: T;
                        };
                    style?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'web-course-list'?:
          | T
          | {
              content?:
                | T
                | {
                    title?: T;
                    courses?: T;
                  };
              settings?:
                | T
                | {
                    spacing?:
                      | T
                      | {
                          marginTop?: T;
                          marginBottom?: T;
                          paddingTop?: T;
                          paddingBottom?: T;
                        };
                    style?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'web-hero-large'?:
          | T
          | {
              content?:
                | T
                | {
                    image?: T;
                    title?: T;
                  };
              settings?:
                | T
                | {
                    spacing?:
                      | T
                      | {
                          marginTop?: T;
                          marginBottom?: T;
                          paddingTop?: T;
                          paddingBottom?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        'web-hero-small'?:
          | T
          | {
              content?:
                | T
                | {
                    image?: T;
                    title?: T;
                    link?:
                      | T
                      | {
                          text?: T;
                          href?: T;
                          target?: T;
                        };
                  };
              settings?:
                | T
                | {
                    spacing?:
                      | T
                      | {
                          marginTop?: T;
                          marginBottom?: T;
                          paddingTop?: T;
                          paddingBottom?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        'web-highlighted-links'?:
          | T
          | {
              content?:
                | T
                | {
                    links?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          image?: T;
                          target?: T;
                          id?: T;
                        };
                  };
              settings?:
                | T
                | {
                    spacing?:
                      | T
                      | {
                          marginTop?: T;
                          marginBottom?: T;
                          paddingTop?: T;
                          paddingBottom?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        'web-image-text'?:
          | T
          | {
              content?:
                | T
                | {
                    title?: T;
                    image?: T;
                    textTop?: T;
                    textHighlight?: T;
                    textBottom?: T;
                    link?:
                      | T
                      | {
                          text?: T;
                          href?: T;
                          target?: T;
                        };
                  };
              settings?:
                | T
                | {
                    spacing?:
                      | T
                      | {
                          marginTop?: T;
                          marginBottom?: T;
                          paddingTop?: T;
                          paddingBottom?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        'web-infos'?:
          | T
          | {
              content?:
                | T
                | {
                    infos?:
                      | T
                      | {
                          infos?:
                            | T
                            | {
                                title?: T;
                                text?: T;
                              };
                          link?:
                            | T
                            | {
                                text?: T;
                                href?: T;
                                target?: T;
                              };
                          id?: T;
                        };
                  };
              settings?:
                | T
                | {
                    spacing?:
                      | T
                      | {
                          marginTop?: T;
                          marginBottom?: T;
                          paddingTop?: T;
                          paddingBottom?: T;
                        };
                    style?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'web-mood-picture'?:
          | T
          | {
              content?:
                | T
                | {
                    image?: T;
                  };
              settings?:
                | T
                | {
                    spacing?:
                      | T
                      | {
                          marginTop?: T;
                          marginBottom?: T;
                          paddingTop?: T;
                          paddingBottom?: T;
                        };
                    style?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'web-swiper-card'?:
          | T
          | {
              content?:
                | T
                | {
                    cards?:
                      | T
                      | {
                          image?: T;
                          info?: T;
                          date?: T;
                          title?: T;
                          link?:
                            | T
                            | {
                                text?: T;
                                href?: T;
                                target?: T;
                              };
                          id?: T;
                        };
                  };
              settings?:
                | T
                | {
                    spacing?:
                      | T
                      | {
                          marginTop?: T;
                          marginBottom?: T;
                          paddingTop?: T;
                          paddingBottom?: T;
                        };
                    style?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'web-swiper-large'?:
          | T
          | {
              content?:
                | T
                | {
                    title?: T;
                    items?:
                      | T
                      | {
                          image?: T;
                          infos?: T;
                          title?: T;
                          description?: T;
                          link?:
                            | T
                            | {
                                text?: T;
                                href?: T;
                                target?: T;
                              };
                          id?: T;
                        };
                  };
              settings?:
                | T
                | {
                    spacing?:
                      | T
                      | {
                          marginTop?: T;
                          marginBottom?: T;
                          paddingTop?: T;
                          paddingBottom?: T;
                        };
                    style?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'web-swiper-simple'?:
          | T
          | {
              content?:
                | T
                | {
                    slides?:
                      | T
                      | {
                          title?: T;
                          images?:
                            | T
                            | {
                                image?: T;
                                id?: T;
                              };
                          id?: T;
                        };
                  };
              settings?:
                | T
                | {
                    spacing?:
                      | T
                      | {
                          marginTop?: T;
                          marginBottom?: T;
                          paddingTop?: T;
                          paddingBottom?: T;
                        };
                    style?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'web-text-element'?:
          | T
          | {
              content?:
                | T
                | {
                    title?: T;
                    content?: T;
                    link?:
                      | T
                      | {
                          text?: T;
                          href?: T;
                          target?: T;
                        };
                  };
              settings?:
                | T
                | {
                    spacing?:
                      | T
                      | {
                          marginTop?: T;
                          marginBottom?: T;
                          paddingTop?: T;
                          paddingBottom?: T;
                        };
                    style?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  description?: T;
  image?: T;
  keywords?: T;
  noIndex?: T;
  canonical?: T;
  schemaType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-partners_select".
 */
export interface WebPartnersSelect<T extends boolean = true> {
  name?: T;
  link?:
    | T
    | {
        text?: T;
        href?: T;
        target?: T;
      };
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-socials_select".
 */
export interface WebSocialsSelect<T extends boolean = true> {
  link?:
    | T
    | {
        text?: T;
        href?: T;
        target?: T;
      };
  icon?: T;
  backgroundImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-books_select".
 */
export interface WebBooksSelect<T extends boolean = true> {
  title?: T;
  infos?: T;
  description?: T;
  cover?: T;
  link?:
    | T
    | {
        text?: T;
        href?: T;
        target?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-text-blocks_select".
 */
export interface WebTextBlocksSelect<T extends boolean = true> {
  slug?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-footer".
 */
export interface WebFooter {
  id: number;
  text1?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  text2?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        text?: string | null;
        href?: string | null;
        target?: ('_self' | '_blank' | '_parent' | '_top' | '_unfencedTop') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-header".
 */
export interface WebHeader {
  id: number;
  links?:
    | {
        text?: string | null;
        href?: string | null;
        target?: ('_self' | '_blank' | '_parent' | '_top' | '_unfencedTop') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-sidebar".
 */
export interface WebSidebar {
  id: number;
  links?:
    | {
        icon?: string | null;
        text?: string | null;
        href?: string | null;
        target?: ('_self' | '_blank' | '_parent' | '_top' | '_unfencedTop') | null;
        id?: string | null;
      }[]
    | null;
  logoLink?: {
    text?: string | null;
    href?: string | null;
    target?: ('_self' | '_blank' | '_parent' | '_top' | '_unfencedTop') | null;
    id?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  name?: string | null;
  phone?: {
    text?: string | null;
    href?: string | null;
  };
  mail?: {
    text?: string | null;
    href?: string | null;
  };
  address?: {
    place?: string | null;
    street?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-footer_select".
 */
export interface WebFooterSelect<T extends boolean = true> {
  text1?: T;
  text2?: T;
  links?:
    | T
    | {
        text?: T;
        href?: T;
        target?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-header_select".
 */
export interface WebHeaderSelect<T extends boolean = true> {
  links?:
    | T
    | {
        text?: T;
        href?: T;
        target?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-sidebar_select".
 */
export interface WebSidebarSelect<T extends boolean = true> {
  links?:
    | T
    | {
        icon?: T;
        text?: T;
        href?: T;
        target?: T;
        id?: T;
      };
  logoLink?:
    | T
    | {
        text?: T;
        href?: T;
        target?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  name?: T;
  phone?:
    | T
    | {
        text?: T;
        href?: T;
      };
  mail?:
    | T
    | {
        text?: T;
        href?: T;
      };
  address?:
    | T
    | {
        place?: T;
        street?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}